/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 100128
 Source Host           : localhost:3306
 Source Schema         : test_db

 Target Server Type    : MySQL
 Target Server Version : 100128
 File Encoding         : 65001

 Date: 13/02/2019 21:24:02
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for tbl_active_file_audit
-- ----------------------------
DROP TABLE IF EXISTS `tbl_active_file_audit`;
CREATE TABLE `tbl_active_file_audit`  (
  `active_file_audit_id` int(11) NOT NULL AUTO_INCREMENT,
  `tbl_huf_id` int(11) NOT NULL,
  `dIEfrm_dt_arvl_patnt_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dIEfrm_dt_arvl_patnt_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dIEfrm_dt_ia_cmplt_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dIEfrm_dt_ia_cmplt_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dIEfrm_pa_ass_scr` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dIEfrm_gsc_scr` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dIEfrm_histry` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dIEfrm_vital` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dIEfrm_vital_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dcp_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dcp_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dcp_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dcp_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dcp_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dn_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dn_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dn_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dn_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dn_vital` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dn_pa_ass_scr` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dn_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nas_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nas_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nas_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nas_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nas_date_arv_ptnt` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nas_time_arv_ptnt` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nas_date_ia_cmplt` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nas_time_ia_cmplt` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nas_pan_ass_scr` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nas_vital` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nas_morse_fall_scale` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nas_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `ncp_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `ncp_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `ncp_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `ncp_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `ncp_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nps_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nps_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nps_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nps_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nps_handovr_tkn_by_from` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nps_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nuAss_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nuAss_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nuAss_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nuAss_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nuAss_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `phys_ass_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `phys_ass_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `phys_ass_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `phys_ass_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `phys_ass_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `medictin_chrt_in_caps` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `medictin_chrt_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `medictin_chrt_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `medictin_chrt_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `medictin_chrt_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `medictin_chrt_risk_vrfd` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `medictin_chrt_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `invstigation_sheet` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btCsnt_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btCsnt_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btCsnt_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btCsnt_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btCsnt_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `resCsnt_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `resCsnt_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `resCsnt_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `resCsnt_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `resCsnt_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `pCsnt_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `pCsnt_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `pCsnt_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `pCsnt_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `pCsnt_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `hivCsnt_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `hivCsnt_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `hivCsnt_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `hivCsnt_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `hivCsnt_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `bcl_cather_frm` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `bcl_ventr_frm` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `bcl_line_frn` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `bcl_ssl_pvnt_frm` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btmf_s_e_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btmf_s_e_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btmf_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btmf_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btmf_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btmf_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btmf_vital` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `btmf_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dmc_vital` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `dmc_ressmnt_scr` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `intak_opt` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `movmnt_sheet` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `restrn_frm` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `patnt_rigt_res_frm` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `patnt_f_e_chrt` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `esti_frm` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `s_c_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `s_c_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `s_c_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `s_c_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `s_c_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `a_c_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `a_c_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `a_c_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `a_c_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `a_c_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `pac` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `anasthsia_care_plan` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `pr_optv_chcklst` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `anasthsia_sfty_chcklst` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `surgn_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `surgn_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `surgn_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `surgn_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `surgn_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `anast_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `anast_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `anast_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `anast_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `anast_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nurse_sign` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nurse_name` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nurse_date` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nurse_time` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `nurse_remarks` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `anaeshts_chart` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `intraptv_mon_rcrd` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `anaeshts_chart1` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `pst_anaeshts_mgmt` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `opertv_notes` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  PRIMARY KEY (`active_file_audit_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

SET FOREIGN_KEY_CHECKS = 1;
